[package]
name = "cast"
version = "0.1.0"
std = "c23"
compiler = "gcc"

[build]
src = ["src/**/*.c", "extern/**/*.c"]
include = ["src", "extern"]
out = "build"

[profile.debug]
flags = ["-g", "-fsanitize=address,undefined", "-D_POSIX_C_SOURCE=200809L"]

[profile.release]
flags = ["-O2", "-DNDEBUG", "-D_POSIX_C_SOURCE=200809L"]

[install]
prefix = "/usr/local"